{% set name = "pwntools" %}
{% set version = "4.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pwntools-{{ version }}.tar.gz
  sha256: 320285bd9266152fdba3b81de3a31e61a25076645507a38d85f34e1b15998eb1

build:
  number: 0
  noarch: python
  entry_points:
    - pwn=pwnlib.commandline.main:main
    - version=pwnlib.commandline.common:main
    - update=pwnlib.commandline.common:main
    - unhex=pwnlib.commandline.common:main
    - template=pwnlib.commandline.common:main
    - shellcraft=pwnlib.commandline.common:main
    - scramble=pwnlib.commandline.common:main
    - pwnstrip=pwnlib.commandline.common:main
    - phd=pwnlib.commandline.common:main
    - main=pwnlib.commandline.common:main
    - hex=pwnlib.commandline.common:main
    - errno=pwnlib.commandline.common:main
    - elfpatch=pwnlib.commandline.common:main
    - elfdiff=pwnlib.commandline.common:main
    - disasm=pwnlib.commandline.common:main
    - disablenx=pwnlib.commandline.common:main
    - debug=pwnlib.commandline.common:main
    - cyclic=pwnlib.commandline.common:main
    - constgrep=pwnlib.commandline.common:main
    - common=pwnlib.commandline.common:main
    - checksec=pwnlib.commandline.common:main
    - asm=pwnlib.commandline.common:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=44.0
  run:
    - paramiko >=1.15.2
    - mako >=1.0.0
    - pyelftools >=0.29
    - capstone >=3.0.5rc2
    - ropgadget >=5.3
    - pyserial >=2.7
    - requests >=2.0
    - pip >=6.0.8
    - pygments >=2.0
    - pysocks
    - python-dateutil
    - packaging
    - psutil >=3.3.0
    - intervaltree >=3.0
    - sortedcontainers
    - python-unicorn >=2.0.1
    - six >=1.12.0
    - rpyc
    - colored-traceback
    - unix-ar
    - zstandard
    - python >=3.6

test:
  # Can't use a regular imports test as due to the issue with the TERM variable
  # imports:
  #   - pwn
  #   - pwnlib
  commands:
    - pip check
    # Avoid errors like "Warning: _curses.error: setupterm: could not find terminfo database"
    - export TERM=xterm
    - python -c 'import pwn'
    - python -c 'import pwnlib'
    - pwn --help
    - version --help
    - update --help
    - unhex --help
    - template --help
    - shellcraft --help
    - scramble --help
    - pwnstrip --help
    - phd --help
    - hex --help
    - errno --help
    - elfpatch --help
    - elfdiff --help
    - disasm --help
    - disablenx --help
    - debug --help
    - cyclic --help
    - constgrep --help
    - checksec --help
    - asm --help
  requires:
    - pip

about:
  home: https://pwntools.com
  summary: Pwntools CTF framework and exploit development library.
  license: MIT
  license_file: LICENSE-pwntools.txt

extra:
  recipe-maintainers:
    - chrisburr
    - pavelzw
    - '0xbe7a'
